### ISSUE TITLE
metrics for jenkins.agents.* are not generated

### ISSUE THREAD

**Issue by v1v** [jenkinsci/opentelemetry-plugin#17] opened 2021-03-09 18:43 UTC
With the latest changes, the metrics for the number of agents (online and offline) are not populated.

**Comment by cyrille-leclerc** [comment] 2021-03-09 20:19
Duplicate of https://github.com/elastic/apm-server/issues/4718

**Comment by cyrille-leclerc** [comment] 2021-03-09 21:10
See fix https://github.com/jenkinsci/opentelemetry-plugin/pull/18

**Closed** 2021-03-09 21:52 UTC
Labels: bug
