### ISSUE TITLE
Kibana dashboards(overview and provisioning) are empty 

### ISSUE THREAD

**Issue by SenthilkumarRasan** [jenkinsci/opentelemetry-plugin#301] opened 2022-01-19 16:50 UTC
There is no data in both dashboards imported from repo.
I see no issue wth traces.
Is there any additional config required to get the metrics data used in dashboards

**Comment by v1v** [comment] 2022-01-20 16:24
Hi @SenthilkumarRasan,

Thanks for your issue, from your description I cannot understand what's exactly the issue about, would you mind to provide further details that can help to understand whether the issue is within the plugin, the dashboards or the setup in your end?

Some questions that could help with this troubleshooting are:

1) Is this issue related to the dashboards, the traces or everything? In other words, do you see any traces when a new build is executed in Jenkins?
2) What OS version/ Jenkins version / ElasticStack / OTel collector have you configured? 
3) Do you see any logs in the Jenkins controller logs or in the APM Server? (I assume ElasticStack is the current setup since you mentioned dashboard)

Thanks

**Comment by wajika** [comment] 2022-03-01 08:50
I have similar doubts, I use helloworld to test on a newly deployed jenkins, this is my first operation, I don't know right or wrong.
After the build I click "View pipeline with Elastic Observability", the browser goes into kibana, but I don't see any data.
I suspect helloworld is not suitable for testing opentelemetry.
We use dotnet language development, that is, do not use maven and Gradle, so is there any simple case to test?

![image](https://user-images.githubusercontent.com/17058349/156134457-3fc18cf4-cfcc-43d6-badf-b42d49db8863.png)
![image](https://user-images.githubusercontent.com/17058349/156134468-69739bfe-ce71-4e3f-8142-7e4564bee9e1.png)
![image](https://user-images.githubusercontent.com/17058349/156134549-9aa0dac0-8582-4d43-aaef-ac3838ed3d71.png)
![image](https://user-images.githubusercontent.com/17058349/156134612-91aeb584-4963-4aa2-9a8e-33754115b7e3.png)

**Comment by v1v** [comment] 2022-03-01 09:09
@wajika , thanks for your comment, If I understood correctly, your issue is a bit different, OpenTelemetry works regardless of the type of jobs, technology or whatsover as long as it runs in Jenkins then traces should be shown.
Would you mind if I ask you to raise a new GitHub issue and provide as much details as possible about your existing environment. please?

**Comment by wajika** [comment] 2022-03-01 09:13
> @wajika , thanks for your comment, If I understood correctly, your issue is a bit different, OpenTelemetry works regardless of the type of jobs, technology or whatsover as long as it runs in Jenkins then traces should be shown. Would you mind if I ask you to raise a new GitHub issue and provide as much details as possible about your existing environment. please?

Do you think the problems are not similar? OK, I'll start a new issue, by the way what other information do I need to provide?

**Comment by v1v** [comment] 2022-03-01 09:17
thanks @wajika, if you go to https://github.com/jenkinsci/opentelemetry-plugin/issues/new/choose then choose a bug issue, there is a form that helps with what details are important

**Comment by cyrille-leclerc** [comment] 2022-03-09 13:29
@wajika can we close this issue?

**Comment by wajika** [comment] 2022-03-10 05:36
> @wajika can we close this issue?

OK

**Closed** 2022-03-10 08:36 UTC
