### ISSUE TITLE
Jenkins logs in elastic APM

### ISSUE THREAD

**Issue by Neelam-zanvar** [jenkinsci/opentelemetry-plugin#534] opened 2022-10-13 06:15 UTC
Hi, I've installed otel plugin on jenkins and installed elastic APM on elk server machine. i want to visualise jenkins logs on elk server. When configuring the plugin i am getting 
![image](https://user-images.githubusercontent.com/98389856/195516403-11e3d31a-def9-424e-8582-a1cee37a5bae.png)

I'am not getting any documentation for using this plugin and configuring it with apm. Please help!

**Comment by v1v** [comment] 2022-10-15 08:33
https://github.com/jenkinsci/opentelemetry-plugin/blob/master/docs/build-logs.md is the main doc regarding configuring the logs.

Regarding the jenkins controller, maybe in the logs you can see some details.

Regarding the elastic stack you also need to check in the logs and discover if any data were sent.

Finally, https://github.com/jenkinsci/opentelemetry-plugin/tree/master/demos is a docker based demo environment with all the required services working together, that could help in terms of whats configured with the OTEL collector,  if that's even something enabled in your end.

Other than that, here is no way we can provide any further help without knowing more about your setup, so we can discard wherher it's a misbehaviour in the plugin or in the setup.

**Comment by Neelam-zanvar** [comment] 2022-10-17 05:09
I am not using the jenkins controller. sending logs from jenkins directly to APM. APM server has no authorization required to connect to it. For elasticsearch authorization is enabled. which ive setup for the plugin but still i am getting the error shown in the image. I've installed otel plugin on jenkins its config shown in image. and on apm side ive only installed apm server on elk machine

**Comment by v1v** [comment] 2022-10-17 11:03
I'm afraid we cannot provide any help with the existing provided information. In telemetry-plugin/issues/535#issuecomment-1280305062 it seems an error is shown when connecting to Elasticsearch `401`.

You can debug the Jenkins OpenTelemetry plugin in Jenkins:

- https://www.jenkins.io/doc/book/system-administration/viewing-logs/#logs-in-jenkins

Then you can enable some of them, for instance the ones defined in:
- https://github.com/jenkinsci/opentelemetry-plugin/blob/dfc6f207c8e77b124c458a72effdb9f6612781e8/demos/config/jenkins.yml#L9-L27


<img width="1556" alt="image" src="https://user-images.githubusercontent.com/2871786/196160849-9a59d52b-c4b5-4bb3-b196-8d6c7f79dd98.png">

and you will get something like:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/2871786/196160948-160732e9-7171-4a00-bb28-f16cc7c825f0.png">

From there, you could see if traces are sent, so you could discard if the problem is coming from the Jenkins Controller, plugin, and it's related to the Elasticstack.


As I mentioned earlier, you can test the demos locally as they are working fine, so once you get familiar with, you could change some of the Jenkins OpenTelmetry plugin configuration to use your ElasticStack, so you can discard if those issues are related to any misconfiguration in the Jenkins side or the Vendor side.

**Comment by v1v** [comment] 2022-10-17 11:43
Not able to reproduce the error locally using the demos environment, see https://github.com/jenkinsci/opentelemetry-plugin/issues/535#issuecomment-1280672826 that contains some details regarding the versions which were used, so I'll close this issue

**Closed by v1v** 2022-10-17 11:43 UTC

**Comment by Neelam-zanvar** [comment] 2022-10-18 04:16
Hi,
How can i grant read permission to elastic(custom) user to index template logs-apm.app as shown in the otel plugin configuration? also it asks me to verify the existence of logs-apm.app index template.



Best regards,

Neelam Zanvar Hanabaratti

Infrastructure & DevOps Engineer

Mobile: +91 8792429745

www.minutuscomputing.com<https://www.minutuscomputing.com/>

________________________________

**Comment by v1v** [comment] 2022-10-18 08:41
> How can i grant read permission to elastic(custom) user to index template logs-apm.app as shown in the otel plugin configuration? also it asks me to verify the existence of logs-apm.app index template.

I'd say to look for those details in the Elastic docs for the version you are using, those details could potentially change between versions so it's not documented here. If you'd like to contribute back to the existing documentation section in this project, and enrich it please feel free to raise a PR with your changes. https://github.com/jenkinsci/opentelemetry-plugin/blob/master/docs/build-logs.md is the main doc file for the logs 🙏
