### ISSUE TITLE
Root span for Jenkins Pipeline (not multibranch) is missing.

### ISSUE THREAD

**Issue by ipleten** [jenkinsci/opentelemetry-plugin#282] opened 2021-12-30 17:13 UTC
### Describe your use-case which is not covered by existing documentation.

When using Jenkins pipeline there is no root span. We can just see some parts of tracing rendered (via NewRelic opentelemetery integration). Therefore for multibracn we able to see whole tracing  but for Pipeline it renders individual stages as standalone tracings.
![image](https://user-images.githubusercontent.com/6207156/147773281-3fbf346f-6023-4e70-bcba-7f2faf7f6ae7.png)

There are a bunch of orphaned spans named 'Phase: Start' and spans nested to it.  
If I select all spans by trace.id it doesn't show root span  and it's properties at all.

**Comment by cyrille-leclerc** [comment] 2022-01-02 22:21
Can you confirm that the missing root span is not a transient problem that happens as long as the build is not completed?
It's a common problem caused by the fact that the OpenTelemetry SDK sends the spans to the observability backend after they end.
If it's not this cause, can you please reproduce with Jaeger?

**Comment by cyrille-leclerc** [comment] 2022-03-13 23:36
@ipleten can you please help us as we don't know how to reproduce? Otherwise, we will have to close this issue as "can't reproduce".

**Comment by cyrille-leclerc** [comment] 2022-04-06 09:00
Hello @ipleten , we run a survey to better understand Jenkins Observability needs and more broadly CI/CD Observability needs, could you by any chance answer it?
https://docs.google.com/forms/d/e/1FAIpQLSezbndR1bpPj4YeWquLLWEYOkEjEI-lSyNbtDUVrR-udpt2lA/viewform?usp=sf_link

**Comment by ipleten** [comment] 2023-10-26 05:19
I'm really sorry about late response.
There is "Phase:XX" stages which seems have only parent.id and name field set. No `jenkins.pipeline.x.x` nor `ci.x.x` so they kinda not stage nor root spans. Just some spans. I suggest to set `jenkins,pipeline.step.name='phase'`.
This is an Json for failed pipeline which hasn't started any stage we have scripted pipeline at the top which later become declerative like:
```
node('init'){do_init}
pipeline{...}
```
So basically there are 4 spans:
This is how it looks like in NewRelic search:
<img width="1326" alt="image" src="https://github.com/jenkinsci/opentelemetry-plugin/assets/6207156/49113eb1-7077-4c6b-909f-6d579a4e71d9">


```[
  {
    "results": [
      {
        "events": [
          {
            "timestamp": 1698291171913,
            "ci.pipeline.name": null,
            "jenkins.pipeline.step.name": null,
            "name": "Phase: Finalise",
            "parent.id": "7d541910eef85346"
          },
          {
            "timestamp": 1698291165728,
            "ci.pipeline.name": null,
            "jenkins.pipeline.step.name": null,
            "name": "Phase: Run",
            "parent.id": "7d541910eef85346"
          },
          {
            "timestamp": 1698291165682,
            "ci.pipeline.name": "pipeline-name",
            "jenkins.pipeline.step.name": null,
            "name": "BUILD pipeline-name",
            "parent.id": null
          },
          {
            "timestamp": 1698291165682,
            "ci.pipeline.name": null,
            "jenkins.pipeline.step.name": null,
            "name": "Phase: Start",
            "parent.id": "7d541910eef85346"
          }
        ]
      }
    ],
    "metadata": {
      "contents": [
        {
          "function": "events",
          "limit": 2000,
          "columns": [
            "timestamp",
            "ci.pipeline.name",
            "jenkins.pipeline.step.name",
            "name",
            "parent.id"
          ],
          "order": {
            "column": "timestamp",
            "descending": true
          }
        }
      ],
      "eventTypes": [
        "Span"
      ],
      "eventType": "Span",
      "openEnded": true,
      "messages": [],
      "beginTimeMillis": 1698253661654,
      "endTimeMillis": 1698296861654,
      "beginTime": "2023-10-25T17:07:41Z",
      "endTime": "2023-10-26T05:07:41Z",
      "guid": "<redact>",
      "routerGuid": "<redact>",
      "rawSince": "12 HOURS AGO",
      "rawUntil": "NOW",
      "rawCompareWith": "",
      "accounts": [
        <redact>
      ]
    },
    "performanceStats": {
      "inspectedCount": 34584,
      "responseTime": 78,
      "exceedsRetentionWindow": false
    }
  }
]
```

Sorry it's really hard to publish more data due to NDA. SecTeam are beasts.

**Comment by kuisathaverat** [comment] 2024-01-03 10:48
Those `Phase:*` spans are marks on where Jenkins is in the execution of the pipeline, they are not related to any step of the pipeline. They are useful to determine the time Jenkins spends on each phase. They no need any additional info to correlate them with the pipeline execution.

<img width="1021" alt="Screenshot 2024-01-03 at 11 47 41" src="https://github.com/jenkinsci/opentelemetry-plugin/assets/5400788/f6f3b2ab-43bd-4422-9ff0-66b8c8fbdc6f">

**Closed by kuisathaverat** 2024-01-03 10:48 UTC
Labels: documentation, backend/newrelic
