### ISSUE TITLE
getting error [id=222]   SEVERE  i.o.s.internal.ThrottlingLogger#doLog: Failed to export spans. The request could not be executed. Full error message: FRAME_SIZE_ERROR: 4740180

### ISSUE THREAD

**Issue by aslodh** [jenkinsci/opentelemetry-plugin#648] opened 2023-05-17 06:55 UTC
Hello Team, 
i have jenkins installed on AKS kubernetes cluster, jenkins is running as pod
I have installed and configure opentelemetry plugin on jenkins and configured as per steps
but getting below error while sending metric to jaeger or any other dashboards.

```
[id=222]   SEVERE  i.o.s.internal.ThrottlingLogger#doLog: Failed to export spans. The request could not be executed. Full error message: FRAME_SIZE_ERROR: 4740180
```

Any suggention on this?

Thank you in advance

**Comment by cyrille-leclerc** [comment] 2023-05-22 21:45
Can you please share more context:
* What's the OTLP destination / which OpenTelemetry backend are you using?
* Can you use an OpenTelemetry Collector next to your Jenkins deployment to ack as a relay to send the traces, logs, and metrics to the OpenTelemetry backend and see if the problem happens again?

**Comment by aslodh** [comment] 2023-05-23 05:35
Hi Cyrille,
* What's the OTLP destination / which OpenTelemetry backend are you using?
-> We are using jaeger as observibility backend, Also we do have installed jenkins in one namespace and open telemetry collector (otlp) in another namespace) on aks kubernetes cluster

* Can you use an OpenTelemetry Collector next to your Jenkins deployment to ack as a relay to send the traces, logs, and metrics to the OpenTelemetry backend and see if the problem happens again?
-> are you saying to install both jenkins and opentelemetry in same namespace? or opentelemetry-java-agent jar as part of jenkins deployment and start jenkins with that opentelemetry jar?

Thank you
 Ashish

**Comment by aslodh** [comment] 2023-05-23 06:17
Hello Cyrille,

I also tried the suggeted thing by you putted jenkins and otel collector in same namespace , but still the issue is same
also one more thing to add here when I have added property "otel.exporter.otlp.protocol=http/protobuf" in opentelemetry plugin configure property section the error got changed, if I keep this property I am getting below error 

_2023-05-23 06:16:45.892+0000 [id=190]   SEVERE  i.o.s.internal.ThrottlingLogger#doLog: Failed to export spans. The request could not be executed. Full error message: unexpected end of stream on http://px-otel-XXXXXXXXXXXXX.com/..._

Thank you 
 Ashish

**Comment by cyrille-leclerc** [comment] 2023-05-23 07:42
@aslodh can you confirm:
* you actually need to use http/protobuff rather than the default gRPC protocol?
* if so, have configured the OpenTelemetry Collector to not only listen on the GRPC endpoint (port 4317 by default) but also listen on the http/protobuff port (port 4318 by default). See documentation [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md#getting-started)
* and have configured the Jenkins OpenTelemetry plugin to send the http/protobuff to this endpoint?

**Comment by aslodh** [comment] 2023-05-24 07:04
Hello Cyrille,
you actually need to use http/protobuff rather than the default gRPC protocol?
-> I tried with both protocols both gives errors, is there any issue if we installed opentelemetry collector on kubernetes and also jenkins on kubernetes (kubernetes version - 1.25.6)

if so, have configured the OpenTelemetry Collector to not only listen on the GRPC endpoint (port 4317 by default) but also listen on the http/protobuff port (port 4318 by default). See documentation [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md#getting-started)

-> Yes I did tried with both ports by configuring ingress for 4317 and 4318 but still not working 

and have configured the Jenkins OpenTelemetry plugin to send the http/protobuff to this endpoint?
- > yes, grpc protocol giving error for frame size then I have enabled http/protobuff endpoint and also added configuration property to enable it "otel.exporter.otlp.protocol=http/protobuf"

but both are not working and getting above errors mentioned in ticket

Thank you
 Ashish

**Comment by aslodh** [comment] 2023-05-30 08:30
Hello Cyrille,
Any update on above issue?

**Comment by kuisathaverat** [comment] 2023-08-01 15:20
It smells like a proxy issue, something like https://stackoverflow.com/questions/63138358/kubernetes-ingress-with-grpc not related to the plugin at all.

**Comment by cyrille-leclerc** [comment] 2023-09-19 22:17
Closing this issue as "can't reproduce", this seems to be a Kubernetes setup issue more than a problem caused by the Jenkins OpenTelemetry plugin.

**Closed by cyrille-leclerc** 2023-09-19 22:17 UTC
